import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
// We need this to import the AblyChatComponent properly
// AblyChatComponent can only run inside the user's browser.
// It connects using WebSockets, and isn't suitable for server side rendering.
// Because server side rendering is NextJS's default, so we use dynamic to
// tell it not to render this during the build process.
import dynamic from 'next/dynamic'
const AblyChatComponent = dynamic(() => import('../components/AblyChatComponent.jsx'), { srr: false })

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Hello!</p>
        <AblyChatComponent />
      </main>
    </>
  )
}
